import{a as p,i as s,S as f}from"./assets/vendor-64b55ca9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&t(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();function m(a){const r=document.querySelector(".gallery"),n=a.map(t=>`
      <div class="photo-card">
        <a href="${t.largeImageURL}" target="_blank">
          <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><i class="img-text">Likes </i><span>${t.likes}</span></p>
          <p><i class="img-text">Views </i><span>${t.views}</span></p>
          <p><i class="img-text">Comments </i><span>${t.comments}</span></p>
          <p><i class="img-text">Downloads </i><span>${t.downloads}</span></p>
        </div>
      </div>
    `).join("");r.innerHTML+=n,d.refresh()}const g="42334631-07f239856d3b6a49db441bfb9";async function h(a,r){const n=document.querySelector(".loader"),t=document.querySelector("#load-more");n.style.display="block",t.style.display="none";try{const e=await p.get(`https://pixabay.com/api/?key=${g}&q=${encodeURIComponent(a)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${r}`);console.log(e.data),n.style.display="none",e.data.hits.length===0?s.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(m(e.data.hits),d.refresh(),t.style.display="block")}catch(e){console.error("Error fetching images:",e),n.style.display="none",s.error({title:"Error",message:"Failed to fetch images. Please try again later."})}}const d=new f(".gallery a"),b=document.querySelector("#search-form"),y=document.querySelector("#search-input");let c="",i=1;b.addEventListener("submit",async a=>{if(a.preventDefault(),c=y.value.trim(),i=1,!c){s.warning({title:"Warning",message:"Please enter a search query"});return}try{await u()}catch(r){console.error("Error fetching images:",r),s.error({title:"Error",message:"Failed to fetch images. Please try again later."})}y.value=""});document.querySelector("#load-more").addEventListener("click",async()=>{i+=1;try{await u()}catch(a){console.error("Error fetching images:",a),s.error({title:"Error",message:"Failed to fetch images. Please try again later."})}});async function u(){const a=document.querySelector(".loader");a.style.display="block";try{const r=await h(c,i);console.log(r.data),a.style.display="none",r.data&&r.data.hits&&r.data.hits.length>0?(appendGalleryMarkup(r.data.hits),d.refresh(),r.data.totalHits<=i*15&&(document.querySelector("#load-more").style.display="none",s.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))):s.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"})}catch(r){console.error("Error fetching images:",r),a.style.display="none",s.error({title:"Error",message:"Failed to fetch images. Please try again later."})}}
//# sourceMappingURL=commonHelpers.js.map
